api_platform:
    title: Test
    version: 1.0.0
    formats:
        json: ['application/json']
    docs_formats:
        html: ['text/html']
    error_formats:
        json: [ 'application/json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    collection:
        # The name of the query parameter to filter nullable results (with the ExistsFilter).
        exists_parameter_name: 'exists'
        # The default order of results.
        order: 'ASC'
        # The name of the query parameter to order results (with the OrderFilter).
        order_parameter_name: 'order'
        pagination:
            # The default name of the parameter handling the page number.
            page_parameter_name: 'page'