version: '3.8'

services:
  cli:
    build:
      context: .docker/cli
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  php-fpm:
    build:
      context: .docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.25.3-alpine3.18
    ports:
      - "127.0.0.1:80:80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/nginx/conf.d/test.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=api
    volumes:
      -  db-data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

volumes:
  db-data:
